# Enable Node.js and PHP
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "php", "git"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "NODE_ENV=production npm run start:railway"
